repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
      args: ["--maxkb=10000"]

# python code formatting
- repo: https://github.com/ambv/black
  rev: 23.9.1
  hooks:
    - id: black

# python code linting
- repo: https://github.com/jsh9/pydoclint
  # pydoclint version.
  rev: 0.3.3
  hooks:
    - id: pydoclint
      args:
        - "--config=pyproject.toml"

# python code linting
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.1
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
