_target_: lightning.pytorch.strategies.DeepSpeedStrategy
zero_optimization: false
stage: 1
allgather_bucket_size: 5e8
reduce_bucket_size: 5e8
offload_optimizer: false
offload_parameters: false
partition_activations: false
cpu_checkpointing: false
