_target_: lightning.pytorch.strategies.DeepSpeedStrategy
zero_optimization: true
stage: 2
allgather_bucket_size: 5e8
reduce_bucket_size: 5e8
offload_optimizer: true
offload_parameters: false
cpu_checkpointing: false
